---
- name: Stop Virtual Machines
  hosts: all
  connection: local
  tasks:
    - name: Stop the Virtual Machine
      community.libvirt.virt:
        name: "{{ inventory_hostname }}"
        state: shutdown
      delegate_to: localhost
