---
- name: Manage Virtual Machines
  hosts: all
  connection: local
  vars:
    vm_state: running
  tasks:
    - name: Ensure the VM is in the desired state
      community.libvirt.virt:
        name: "{{ inventory_hostname }}"
        state: "{{ vm_state }}"
      delegate_to: localhost
