---
- name: Decommission System
  hosts: all
  become: true
  tasks:
    - name: Remove subscriptions
      community.general.redhat_subscription:
        state: absent
    - name: Check Tailscale presence
      ansible.builtin.stat:
        path: /usr/bin/tailscale
      register: check_tailscale
    - name: Logout of tailscale
      ansible.builtin.command: tailscale logout
      when: check_tailscale.stat.exists
