---
- name: Subscribe RHEL system
  hosts: all
  become: true
  vars:
    lnx_soe_decommission_system: false
  tasks:
    - name: Register with activationkey and consume subscription
      community.general.redhat_subscription:
        state: present
        activationkey: "{{ vault_activationkey }}"
        org_id: "{{ vault_org_id }}"

    - name: Remove Subscriptions
      community.general.redhat_subscription:
        state: absent
      when: lnx_soe_decommission_system
